### ISSUE TITLE
Count.ly server leaving thousands of orphaned db connections

### ISSUE THREAD

**Issue by GlennAustin** [Countly/countly-server#267] opened 2016-06-21 16:34 UTC
Having problems with count.ly api.js apparently abandoning thousands of mongodb connections over a 3-minute timespan. Ending api.js has left 1993 db connections open after 3 minutes -- which makes mongodb unable to handle many new connections.

**Comment by gorkem-cetin** [comment] 2016-06-21 18:08
Glenn, can you write which Countly version you are using and on which OS / version ? MongoDB version also helps.

**Comment by GlennAustin** [comment] 2016-06-22 00:12
Count.ly community server 16.02.1
MongoDB version 3.2.7
Mac OS X 10.11.5 + Server 5.1.5
Node.JS 6.2.1

**Comment by GlennAustin** [comment] 2016-06-22 03:46
Workaround - setting api's maxPoolSize to 200 and reducing the maxSockets keeps the server alive.

**Comment by gorkem-cetin** [comment] 2016-06-22 05:36
Never seen anything like that on an Ubuntu / CentOS server - could be Mac specific and we do not support installing on a Mac. Chances are this bug is introduced lately and is reproduced in certain circumstances. Leaving it open so others could see & comment.

**Comment by osoner** [comment] 2016-06-22 07:59
Pool size concept (or the way mongoskin handles them) changed for MongoDB 3.2. @ar2rsawseen we should reduce the default pool size in configs, I think we already discussed this?

**Comment by ar2rsawseen** [comment] 2016-06-22 08:12
I think the problem is that we used mongodb 3.0 for those releases.
I just only recently upgraded drivers and mongodb to 3.2

And testing it now with dev code, seems to work correctly:

![image](https://cloud.githubusercontent.com/assets/399992/16259215/3c6258e2-386a-11e6-8059-679b3e51a5bb.png)

**Comment by ar2rsawseen** [comment] 2016-06-22 08:34
So the current behavior with newest driver and mongodb 3.2 seems to be
(according to lsof and db.serverStatus().connections)

Whole pool size is not allocated at start, but rather connections are opened per need bases.

Once connection is opened it does not close and is kept alive for pool purposes

once we stop countly processes, all connections are closed.

Which seems to be exactly what we need :)

**Comment by GlennAustin** [comment] 2016-06-22 16:57
The Count.ly server appears to be opening between 6x and 7x number of connections designated in the connection pool size.
As far as using a Mac as a server, the only real difference is that instead of using apt-get, Mac users need to install and use a secondary package manager like brew or macports. Virtually everything else "just works" -- because "under the hood," macOS is UNIX.

**Comment by ar2rsawseen** [comment] 2016-06-23 08:27
So I assume it is mismatch of DB version and drivers and/or mongoskin.
Cause previous releases were made fro MongoDB 3.0

and now this next release will be for MongoDB 3.2

And as tested now, connections do not go over pool limit.

BTW about pool limit, there are 3 pool limits, for frontend, for api and enterprise customers have drill connection too.

And what ever is in your config as pool size, it should be multiplied by CPU cores.

so if you have 10 for frontend, 200 for api and 200 for drill and have 4 core cpu, you should have totally up to:

(10 + 200 + 200) * 4 = 1640 connections

so closing issue for now, if it happens with next version too, please reopen

**Closed by ar2rsawseen** 2016-06-23 08:27 UTC
