### ISSUE TITLE
maybe https://dl.google.com ?

### ISSUE THREAD

**Issue by zfavourite99** [Countly/countly-server#1027] opened 2019-08-20 08:08 UTC
system info : centos 6.10
countly version : 19.08

Setting up Install Process
http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: (28, 'Operation too slow. Less than 1 bytes/sec transfered the last 3 seconds')
Trying other mirror.

google chrome repo auto installed by countly install script. the base url maybe use https.

**Comment by ar2rsawseen** [comment] 2019-08-20 11:52
Closing this as duplicate of https://github.com/Countly/countly-server/issues/1028

**Closed by ar2rsawseen** 2019-08-20 11:52 UTC
