### ISSUE TITLE
Stuck when using one line installation on centos: Finding dependency for libwayland-egl.so.1

### ISSUE THREAD

**Issue by Songkeys** [Countly/countly-server#808] opened 2019-02-01 04:33 UTC
```
wget -qO- http://c.ly/install | bash
```

Stuck when using one line installation above. The log shows:

```
Extracting pcre...
Finding dependency for libwayland-egl.so.1
http://: Invalid host name.
Extracting mesa-libwayland-egl
libwayland-egl...
rpm2cpio: mesa-libwayland-egl: No such file or directory
Finding dependency for libwayland-egl.so.1
Finding dependency for libwayland-egl.so.1
Finding dependency for libwayland-egl.so.1
Finding dependency for libwayland-egl.so.1
Finding dependency for libwayland-egl.so.1
Finding dependency for libwayland-egl.so.1
....(keeps repeating)
```

System: Centos 6

**Comment by ar2rsawseen** [comment] 2019-02-01 08:48
Hello,
I can reproduce it. Will look into it.

**Comment by cs-sel** [comment] 2019-06-06 10:36
Same problem on RHEL 6.10 when installing from tar.

Is there a solution yet?

**Comment by gorkem-cetin** [comment] 2019-06-06 17:56
@cs-sel is there an option to use RHEL 7.0 + or RHEL 6.9 + on your side?

**Comment by cs-sel** [comment] 2019-06-07 15:35
@gorkem-cetin does it work with the mentioned operating system versions? We would have to sell our customer another server with RHEL 7, so it would be better to use an existing machine.

**Comment by ar2rsawseen** [comment] 2019-06-07 15:41
The problem seems to be on all Centos/RHEL 6 versions.
And it seems that it works fine on Centos/RHEL 7 versions
But in overall this dependency only is needed from headless browser rendering to take screenshots of dashboard in email reports.
If you can live without it, then omitting this line:
https://github.com/Countly/countly-server/blob/master/bin/countly.install_rhel.sh#L22
Should install countly correctly, without ability to get screenshots in email reports

**Comment by gorkem-cetin** [comment] 2019-06-07 23:39
@cs-sel can you drop me an email to gc@count.ly so we can work with you to make sure your requirements are met and that all the technical issues are cleared up. I'll close this issue for now but let's move forward via email.

**Closed by gorkem-cetin** 2019-06-07 23:39 UTC
