### ISSUE TITLE
Countly installer is broken

### ISSUE THREAD

**Issue by Klaudioz** [Countly/countly-server#3453] opened 2022-08-24 15:41 UTC
### Expected Behavior
Install the server

### Current Behavior
It's not possible to install it.

### Screenshots (if appropriate):
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/632625/186461516-69309e69-576d-4f89-b91e-4e89341eba4a.png">

### Possible Solution
Fix how the URL is being parsed.
Running this: `wget -qO- https://api.github.com/repos/countly/countly-server/releases/latest | grep browser_download_url` is giving an empty string. Probably GitHub made some changes to the JSON response.

### Steps to Reproduce (for bugs)

1. `wget -qO- https://c.ly/install | bash`

Downloading from Github...
http://: Invalid host name.

### Your Environment

* Operating System and version: Ubuntu 20.04
* Any changes you have made to your instance: Clean instance

**Comment by apapalillo** [comment] 2022-08-24 17:06
I'm having the same issue on a fresh Debian 11 instance

**Comment by windware-ono** [comment] 2022-09-03 02:52
It's because the release no longer includes the tarball in the assets and `browser_download_url` is no longer present in the GitHub API response.

It should've been broken since 29 days ago and it's not yet fixed, which is a concern that they don't care people to try out their product, not to mention no support of Ubuntu 22.04 yet.

Temporary fix diff.

```
25c25
<     LATEST=$(wget -qO- https://api.github.com/repos/countly/countly-server/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4) ;
---
>     LATEST=$(wget -qO- https://api.github.com/repos/countly/countly-server/releases/latest | grep tarball_url | head -n 1 | cut -d '"' -f 4) ;
52a53
> EXPANDED_DIR=$(ls -d Countly-countly-server-*)
54c55
<     bash countly/bin/countly.install.sh 2>&1 | tee "countly/log/countly-install-$DATE.log"
---
>     bash $EXPANDED_DIR/bin/countly.install.sh 2>&1 | tee "$EXPANDED_DIR/log/countly-install-$DATE.log"
56c57
<     bash countly/bin/countly.install_rhel.sh 2>&1 | tee "countly/log/countly-install-$DATE.log"
---
>     bash $EXPANDED_DIR/bin/countly.install_rhel.sh 2>&1 | tee "$EXPANDED_DIR/log/countly-install-$DATE.log"
```

**Comment by windware-ono** [comment] 2022-09-03 03:07
The DigitalOcean link is broken and even if you get there manually, the version is more than 2 years old.

http://do.count.ly/

**Comment by kaanklky** [comment] 2022-09-03 07:21
Hello everyone,
First of all, thanks for your help to detect & identify the root cause of the issue.
I merged the PR(#3470)  which fixes this issue and also added a check if URL is exist or not. /cc @windware-ono :)

About Ubuntu 22 support:
We try to support at least last 2 major versions and of course 'support' doesn't mean just writing an installer so our supported versions decided by status of current user base. We will start to support Ubuntu 22 when we can't drop support for Ubuntu 18.

**Closed by kaanklky** 2022-09-03 07:21 UTC

**Comment by windware-ono** [comment] 2022-09-03 08:19
Thanks.

Just a friendly reminder but if you're going to embed some unknown Chinese server looking URL, you might want to put a comment not to scare people off.

I assume by checking if "google.com" is reachable, you're checking if the download is initiated within China and in that case it's using a Chinese CDN to download.

**Comment by kaanklky** [comment] 2022-09-03 08:20
Thanks for the advice.
