### ISSUE TITLE
can't download the export in non-english way

### ISSUE THREAD

**Issue by liangjie18430** [Countly/countly-server#314] opened 2017-07-13 07:37 UTC
select non-english env.select management-->system logs-->download in csv. Get 502 .

**Comment by ar2rsawseen** [comment] 2017-07-13 08:02
I see, 502 is server error, is there any error under error logs? Manegement -> Errors. Under both api log, most probably.
Also is it for 17.05.1? Because there were some fixes related to exporting in 17.05.1

**Comment by liangjie18430** [comment] 2017-07-13 09:21
error log like this:

2017-07-13T09:12:12.968Z: INFO	[jobs:scanner]	Checking plugins ["mobile","web","desktop","plugins","density","locale","browser","sources","views","enterpriseinfo","logger","systemlogs","errorlogs","populator","reports","crashes","push","star-rating","slipping-away-users","compare","server-stats","dbviewer","assistant"]
Caught exception: {} TypeError: The header content contains invalid characters
    at storeHeader (_http_outgoing.js:319:11)
    at ServerResponse.OutgoingMessage._storeHeader (_http_outgoing.js:228:9)
    at ServerResponse.writeHead (_http_server.js:221:8)
    at Object.exports.output (/root/countly/api/parts/data/exports.js:105:20)
    at Object.options.output (/root/countly/api/parts/data/exports.js:244:68)
    at Object.exports.fromData (/root/countly/api/parts/data/exports.js:250:21)
    at /root/countly/api/api.js:1143:65
    at /root/countly/api/api.js:645:13
    at /root/countly/plugins/pluginManager.js:770:25
    at handleCallback (/root/countly/node_modules/mongodb/lib/utils.js:120:56)
    at /root/countly/node_modules/mongodb/lib/collection.js:1417:5
    at handleCallback (/root/countly/node_modules/mongodb/lib/utils.js:120:56)
    at /root/countly/node_modules/mongodb/lib/cursor.js:682:5
    at handleCallback (/root/countly/node_modules/mongodb-core/lib/cursor.js:171:5)
    at nextFunction (/root/countly/node_modules/mongodb-core/lib/cursor.js:682:5)
    at /root/countly/node_modules/mongodb-core/lib/cursor.js:593:7
2017-07-13T09:18:56.609Z: ERROR	[api]	Logging caught exception
2017-07-13T09:18:56.881Z: INFO	[jobs:handle]	Starting job handle in 10455


i can't upgrade to 17.05.1, my version is 17.05

**Comment by ar2rsawseen** [comment] 2017-07-13 09:39
Yes, this issue was fixed in 17.05.1

Don't know why you can't upgrade to new release, but best I can do is to point you to commits made to fix this. Please try applying these commits:

https://github.com/Countly/countly-server/commit/91e9f6f2f3a19097e39bad8e87c5e302dc5f0725
https://github.com/Countly/countly-server/commit/cce19bee8091aad38836252a4c0e16562db15382

And feel free to reopen the issue if you still have problems

**Closed by ar2rsawseen** 2017-07-13 09:39 UTC

**Comment by liangjie18430** [comment] 2017-07-18 02:37
thank you very much!the upgrade method i just type"countly upgrade",i try the commit to the file,the 502 problem has fixed yet.but the new problem is characters(non-english)  in .csv file   are not displayed 
 properly.

**Comment by ar2rsawseen** [comment] 2017-07-18 07:29
Are charactes unicode? Countly only support UTF-8

**Comment by liangjie18430** [comment] 2017-07-18 07:52
I tested with Chinese characters, my operations like this: management-->events log-->export-->export as csv. The chinese characters displayed not properly.    but management-->events log-->export-->export as xls, the characters was correct.

**Comment by ar2rsawseen** [comment] 2017-07-18 07:53
Ok, I see, will recheck

**Comment by ar2rsawseen** [comment] 2017-07-18 08:56
So I switch language to Chinese and try to export something in CSV and it seem to work correctly:
![image](https://user-images.githubusercontent.com/399992/28308824-16f91aa8-6bb0-11e7-80ad-c533ff7d7bd5.png)

Any tips on how to reproduce it?

**Comment by liangjie18430** [comment] 2017-07-20 01:21
thank you, i will check my environment or try it in other machines.

**Comment by liangjie18430** [comment] 2017-07-20 01:32
while i opened with excel ,then the problem emerged ，with sublime,it's okay.thanks.my problem has solved.
