### ISSUE TITLE
[push] Messages with conditions not flagged as sent nor delivered and they are undeletable

### ISSUE THREAD

**Issue by meltaweel** [Countly/countly-server#206] opened 2015-10-15 09:56 UTC
When i send messages using **Drill** it works and notification is received in the test device but it doesn't show in dashboard as sent nor delivered and it stuck at 0%. While sending from **Messages** to all devices is appear as **Sent** and also when it delivered to the devices it updates the status of delivery rate right!

<img width="1032" alt="screen shot 2015-10-15 at 8 38 01 am" src="https://cloud.githubusercontent.com/assets/11625007/10506393/d40039c6-7317-11e5-9538-f3a139b6f76f.png">

Message "test from messages" was sent from **Messages** page.
Messages "test carrier" and "test s4" was sent from **Drill** page by adding condition for carrier and device respectively.

Also we cannot delete those buggy messages from dashboard. when i click delete button it just greyed out and the pop up doesn't hide. while the other messages that have been sent from Messages page are deletable. 

When i checked the chrome developer tools. i found that the api call "pushes/delete" for this buggy messages gives "Bad Gateway" as a response. ( no errors in api log ! ).

When checked the "pushes/create" request that has been sent from Create Message in Drill page and re-sent it using Postman myself, the same problem happens, but when removing the conditions object from the args json object the message works normally ( delivery percentage , sending status and  deletion ).

That was tested only on an Android devices running the demo app "app-messaging" in test mode. 

Edition : **Countly Enterprise Edition**
Version :  **v15.06**

Steps to re-produce : 
1. Go to Drill.
2. Apply any condition and click create message.
3. Check Send to test devices.
4. Click Send.
5. Message is received in the mobile device successfully.
6. Message Sent and Delivery statuses in Messages page doesn't update and stuck at 0%.

**Comment by gorkem-cetin** [comment] 2015-10-18 17:41
Can you support a short email about this issue to support@count.ly and we will handle this issue via email? 

Thanks!

**Comment by meltaweel** [comment] 2015-10-25 23:30
Issue was already sent by email ! is it confirmed and fixed or still

**Comment by iartem** [comment] 2015-10-26 12:13
Hi Muhammad,
Yes, it's confirmed. But not yet committed due to further complications associated with it. Let me know if you need it asap, I'll provide you with a quick fix.

**Comment by iartem** [comment] 2015-10-29 12:06
@meltaweel, it's fixed now in HEAD.

**Closed by iartem** 2015-10-29 12:06 UTC

**Comment by meltaweel** [comment] 2015-10-29 23:01
@iartem  Thanks a lot :+1:
